import { signIn } from "next-auth/react";
import Head from "next/head";
import React from "react";

const Login = () => {
	return (
		<div>
			<Head>
				<title>Next Auth0 demo</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<button onClick={() => signIn("auth0")}>Sign in</button>
		</div>
	);
};

export default Login;
