
import Head from "next/head";

import { signIn } from "next-auth/react";


 function Home() {
  return (
    <div >
      <Head>
        <title>Next Auth0 demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => signIn('auth0')}>Sign in</button>
    </div>
  );
}
export default Home;
